set -v

R_ID="$WERCKER_DISTELLI_DEPLOY_BRANCH_RELEASE_ID"
DEPLOY_BRANCH="master"

if [ -n "$WERCKER_DISTELLI_DEPLOY_BRANCH_BRANCH" ]; then
  DEPLOY_BRANCH = "$WERCKER_DISTELLI_DEPLOY_BRANCH_BRANCH"
fi

if [ -n "$WERCKER_DISTELLI_DEPLOY_BRANCH_DISTELLI_APP" ]; then 
  DISTELLI_APP = $WERCKER_DISTELLI_DEPLOY_BRANCH_DISTELLI_APP
fi

if [ -n "$WERCKER_DISTELLI_DEPLOY_BRANCH_DISTELLI_ENV" ]; then
  DISTELLI_ENV = $WERCKER_DISTELLI_DEPLOY_BRANCH_DISTELLI_ENV
fi

if [ "$WERCKER_GIT_BRANCH" == "$DEPLOY_BRANCH" ]; then
echo bananas
fi
